### ISSUE TITLE
请作者看看。无法安装2.0

### ISSUE THREAD

**Issue by xjdata** [weyii/yii2-filesystem#2]
默认安装好是1.X的.
就算comoposer中指定了2.0。
但是提示找不到版本。"minimum-stability": "stable",  需要dev吗？
或者已经有了2.0的tag。麻烦看看具体原因吧。谢谢。

**Comment by forecho** [comment]
你是怎么安装的，我直接在项目根目录输入下面命令安装是正常的：

```
composer require weyii/yii2-filesystem
```

最后安装的是 2.0

**Comment by xjdata** [comment]
呃.... 可能昨天网络不太对。。。。不好意思了。
